# .goreleaser.yml
version: 2

project_name: terraform-provider-biot-gen2

builds:
  - id: biot-gen2
    main: .
    binary: terraform-provider-biot-gen2
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s -w -X main.version={{.Version}}"

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "SHA256SUMS"

# signs:
#   - artifacts: checksum
#     args: ["--detach-sign", "--default-key", "7C56BDFFED7D41BE"]
#     cmd: gpg
#     signature: "${artifact}.sig"

# before:
#   hooks:
#     - gpg --detach-sign --armor --default-key 7C56BDFFED7D41BE dist/SHA256SUMS && mv dist/SHA256SUMS.asc dist/SHA256SUMS.sig

release:
  github:
    owner: biot-med
    name: terraform-provider-biot-gen2

publishers:
  - name: sign-checksums
    cmd: gpg --detach-sign --armor --default-key 7C56BDFFED7D41BE dist/SHA256SUMS && mv dist/SHA256SUMS.asc dist/SHA256SUMS.sig
    extra_files:
      - dist/SHA256SUMS.sig
