# .goreleaser.yml
version: 2

project_name: terraform-provider-biot-gen2

builds:
  - id: biot-gen2
    main: .
    binary: terraform-provider-biot-gen2
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s -w -X main.version={{.Version}}"

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "SHA256SUMS"

before:
  hooks:
    - 'echo "${GPG_PASSPHRASE}" | gpg --batch --yes --pinentry-mode loopback --passphrase-fd 0 --detach-sign --armor --default-key 7C56BDFFED7D41BE dist/SHA256SUMS && mv dist/SHA256SUMS.asc dist/SHA256SUMS.sig'

release:
  github:
    owner: biot-med
    name: terraform-provider-biot-gen2
