# .goreleaser.yml
version: 2

project_name: terraform-provider-biot-gen2

builds:
  - id: biot-gen2
    main: .
    binary: terraform-provider-biot-gen2
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s -w -X main.version={{.Version}}"

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "SHA256SUMS"

# signs:
#   - artifacts: checksum
#     args: ["--detach-sign"]
#     cmd: gpg
#     signature: "${artifact}.sig"

release:
  github:
    owner: biot-med
    name: terraform-provider-biot-gen2

terraform_registries:
  - provider: "biot-med/biot-gen2"
    owner: "biot-med"
    namespace: "biot-med"
    name: "biot-gen2"
    registry_tiers:
      - "public"
