// Package abac holds what the access-control resources share. Each resource lives in its own
// subpackage - condition, and later action and rule - and describes itself with an Entity.
package abac

import (
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/diag"

	abacapi "biot.com/terraform-provider-biot-gen2/internal/api/abac"
	"biot.com/terraform-provider-biot-gen2/internal/api/transport"
)

// Entity describes one access-control resource type to the shared helpers: the labels used
// in messages, and the error codes the service returns for it.
//
// The codes are spelled out per entity rather than derived from the noun, because the
// service is not consistent about them - conditions report CONDITIONS_NOT_FOUND but rules
// report RULE_NOT_FOUND, and rules have no INVALID_*_VALUE at all. Leave a code empty when
// the entity has no such error. See AccessControlErrorCodes.java in gen2-access-control-service.
type Entity struct {
	// Noun is the human-readable singular name, e.g. "condition".
	Noun string
	// ResourceType is the Terraform type name, e.g. "biot_abac_condition".
	ResourceType string

	AlreadyExistsCode       string
	NotFoundCode            string
	InvalidValueCode        string
	CannotDeleteBuiltInCode string
}

// AddError translates an access-control API error into a Terraform diagnostic, replacing the
// raw server message with something actionable where we can.
//
// operation is the verb being attempted ("create", "read", "update", "delete").
func AddError(diagnostics *diag.Diagnostics, entity Entity, operation string, id string, err error) {
	apiError, ok := transport.AsAPIError(err)
	if !ok {
		diagnostics.AddError(
			"API Error",
			fmt.Sprintf("Failed to %s %s %q: %s", operation, entity.Noun, id, err),
		)
		return
	}

	// Best effort: an error without details, or with details we cannot read, still gets a
	// message below - just a less specific one.
	var details abacapi.ErrorDetails
	_ = apiError.DecodeDetails(&details)

	is := func(code string) bool { return code != "" && apiError.Code == code }

	switch {
	case is(entity.AlreadyExistsCode):
		diagnostics.AddError(
			fmt.Sprintf("The %s %q already exists in BioT", entity.Noun, id),
			fmt.Sprintf(`A %s with id %q already exists on the server, but is not in Terraform state.

ABAC ids are chosen by you rather than generated by the server, and BioT ships a large set
of built-in objects, so colliding with an existing id is easy to do by accident.

Either choose a different id, or adopt the existing object into state:

    terraform import %s.<name> %s

Server said: %s`, entity.Noun, id, entity.ResourceType, id, apiError.Message),
		)

	case is(entity.CannotDeleteBuiltInCode):
		diagnostics.AddError(
			fmt.Sprintf("Cannot delete the built-in %s %q", entity.Noun, id),
			fmt.Sprintf(`%q is tagged as built-in by BioT and cannot be deleted. Built-in objects can be
imported and updated, but never destroyed.

To stop managing it without deleting it:

    terraform state rm %s.<name>

Server said: %s`, id, entity.ResourceType, apiError.Message),
		)

	case is(entity.InvalidValueCode):
		// The server message already enumerates every supported value, so pass it through.
		diagnostics.AddError(
			fmt.Sprintf("Invalid %s value %q", entity.Noun, details.Value),
			apiError.Message,
		)

	case is(entity.NotFoundCode):
		diagnostics.AddError(
			fmt.Sprintf("The %s %q was not found", entity.Noun, id),
			fmt.Sprintf(`BioT has no %s with id %q. It may have been deleted outside of Terraform.

Server said: %s`, entity.Noun, id, apiError.Message),
		)

	default:
		diagnostics.AddError(
			"API Error",
			fmt.Sprintf("Failed to %s %s %q: %s", operation, entity.Noun, id, apiError),
		)
	}
}
