package condition

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"biot.com/terraform-provider-biot-gen2/internal/api"
	"biot.com/terraform-provider-biot-gen2/internal/api/transport"
	"biot.com/terraform-provider-biot-gen2/internal/resources/abac"
	biotplanmodifiers "biot.com/terraform-provider-biot-gen2/internal/resources/biot_plan_modifiers"
)

var (
	_ resource.Resource                   = &BiotAbacConditionResource{}
	_ resource.ResourceWithConfigure      = &BiotAbacConditionResource{}
	_ resource.ResourceWithImportState    = &BiotAbacConditionResource{}
	_ resource.ResourceWithValidateConfig = &BiotAbacConditionResource{}
)

// Entity describes conditions to the shared abac helpers.
var Entity = abac.Entity{
	Noun:                    "condition",
	ResourceType:            "biot_abac_condition",
	AlreadyExistsCode:       "CONDITION_ALREADY_EXISTS",
	NotFoundCode:            "CONDITIONS_NOT_FOUND",
	InvalidValueCode:        "INVALID_CONDITION_VALUE",
	CannotDeleteBuiltInCode: "CANNOT_DELETE_BUILTIN_CONDITION",
}

func NewResource() resource.Resource {
	return &BiotAbacConditionResource{}
}

type BiotAbacConditionResource struct {
	client *api.APIClient
}

func (r *BiotAbacConditionResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = "biot_abac_condition"
}

// The response of this function is passed to every condition resource when running
// create / read / update / delete. The input is the return of the ProviderConfigure function.
func (r *BiotAbacConditionResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*api.APIClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data Type", "Expected *api.APIClient")
		return
	}

	r.client = client
}

func (r *BiotAbacConditionResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "An access-control (ABAC) condition, which decides whether the " +
			"actions of a rule apply to a given request.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Required: true,
				MarkdownDescription: "Unique id for the condition, chosen by you rather than " +
					"generated by BioT (for example `IS_SELF_PATIENT`). The API cannot change " +
					"an id, so changing it here destroys and recreates the condition.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"value": schema.StringAttribute{
				Required: true,
				MarkdownDescription: "Name of the condition implementation, for example " +
					"`InitiatorAttributeInParamsCondition` or `CompositeCondition`. Only " +
					"`DYNAMIC` and `COMPOSITE` implementations can be created - BioT rejects " +
					"the built-in `CLASS` ones, and the error lists everything it accepts. " +
					"The API cannot change a value, so changing it here destroys and " +
					"recreates the condition.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"description": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Default:             stringdefault.StaticString(""),
				MarkdownDescription: "Free-text description. Defaults to an empty string.",
			},
			"params": schema.StringAttribute{
				Optional: true,
				Computed: true,
				Default:  stringdefault.StaticString("{}"),
				MarkdownDescription: "Parameters for the condition implementation, as a JSON " +
					"object. Build it with `jsonencode({...})`; formatting differences are " +
					"normalized away and will not show up as a diff.",
				PlanModifiers: []planmodifier.String{
					biotplanmodifiers.JsonNormalizePlanModifier{},
				},
			},
			"tags": schema.SetAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
				MarkdownDescription: "Tags applied to the condition. Removing this from your " +
					"configuration keeps the tags BioT already has; set it to `[]` to clear " +
					"them.\n\nThe `<<BuiltIn>>` tag that BioT puts on its own conditions is " +
					"not included here and cannot be set - use the `built_in` attribute " +
					"instead.",
			},
			"built_in": schema.BoolAttribute{
				Computed: true,
				MarkdownDescription: "Whether BioT ships this condition. Built-in conditions " +
					"can be imported and updated, but not destroyed.",
				PlanModifiers: []planmodifier.Bool{
					// Whether a condition is built-in never changes, so keep the known value
					// rather than replanning it as "(known after apply)" on every change.
					boolplanmodifier.UseStateForUnknown(),
				},
			},
		},
	}
}

// ValidateConfig rejects the built-in marker in tags - see abac.RejectBuiltInTag.
func (r *BiotAbacConditionResource) ValidateConfig(ctx context.Context, req resource.ValidateConfigRequest, resp *resource.ValidateConfigResponse) {
	var config TerraformAbacCondition

	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	abac.RejectBuiltInTag(config.Tags, Entity, &resp.Diagnostics)
}

func (r *BiotAbacConditionResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan TerraformAbacCondition

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	createRequest, diags := MapTerraformConditionToCreateRequest(ctx, plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	response, err := r.client.Abac.CreateCondition(ctx, createRequest)
	if err != nil {
		abac.AddError(&resp.Diagnostics, Entity, "create", plan.ID.ValueString(), err)
		return
	}

	model, diags := MapConditionResponseToTerraformModel(ctx, response)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, model)...)
}

func (r *BiotAbacConditionResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state TerraformAbacCondition

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	response, err := r.client.Abac.GetCondition(ctx, state.ID.ValueString())
	if err != nil {
		if transport.IsNotFound(err) {
			// Gone from the backend - drop it from state so Terraform plans a create.
			resp.State.RemoveResource(ctx)
			return
		}
		abac.AddError(&resp.Diagnostics, Entity, "read", state.ID.ValueString(), err)
		return
	}

	model, diags := MapConditionResponseToTerraformModel(ctx, response)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, model)...)
}

func (r *BiotAbacConditionResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan TerraformAbacCondition

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	updateRequest, diags := MapTerraformConditionToUpdateRequest(ctx, plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	response, err := r.client.Abac.UpdateCondition(ctx, plan.ID.ValueString(), updateRequest)
	if err != nil {
		abac.AddError(&resp.Diagnostics, Entity, "update", plan.ID.ValueString(), err)
		return
	}

	model, diags := MapConditionResponseToTerraformModel(ctx, response)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, model)...)
}

func (r *BiotAbacConditionResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state TerraformAbacCondition

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	err := r.client.Abac.DeleteCondition(ctx, state.ID.ValueString())
	if err != nil {
		if transport.IsNotFound(err) {
			// Already gone - deleting it is exactly what we wanted.
			return
		}
		abac.AddError(&resp.Diagnostics, Entity, "delete", state.ID.ValueString(), err)
	}
}

// Conditions are imported by their id, which is the same id used in the configuration.
func (r *BiotAbacConditionResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
