package action

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"biot.com/terraform-provider-biot-gen2/internal/api"
	"biot.com/terraform-provider-biot-gen2/internal/api/transport"
	"biot.com/terraform-provider-biot-gen2/internal/resources/abac"
	biotplanmodifiers "biot.com/terraform-provider-biot-gen2/internal/resources/biot_plan_modifiers"
)

var (
	_ resource.Resource                   = &BiotAbacActionResource{}
	_ resource.ResourceWithConfigure      = &BiotAbacActionResource{}
	_ resource.ResourceWithImportState    = &BiotAbacActionResource{}
	_ resource.ResourceWithValidateConfig = &BiotAbacActionResource{}
	_ resource.ResourceWithModifyPlan     = &BiotAbacActionResource{}
)

// Entity describes actions to the shared abac helpers.
var Entity = abac.Entity{
	Noun:                    "action",
	ResourceType:            "biot_abac_action",
	AlreadyExistsCode:       "ACTION_ALREADY_EXISTS",
	NotFoundCode:            "ACTIONS_NOT_FOUND",
	InvalidValueCode:        "INVALID_ACTION_VALUE",
	CannotDeleteBuiltInCode: "CANNOT_DELETE_BUILTIN_ACTION",
}

func NewResource() resource.Resource {
	return &BiotAbacActionResource{}
}

type BiotAbacActionResource struct {
	client *api.APIClient
}

func (r *BiotAbacActionResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = "biot_abac_action"
}

// The response of this function is passed to every action resource when running
// create / read / update / delete. The input is the return of the ProviderConfigure function.
func (r *BiotAbacActionResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*api.APIClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data Type", "Expected *api.APIClient")
		return
	}

	r.client = client
}

func (r *BiotAbacActionResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "An access-control (ABAC) action: what a rule does to a " +
			"request or its response once the rule's conditions are met, such as adding a " +
			"search filter or removing attributes.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Required: true,
				MarkdownDescription: "Unique id for the action, chosen by you rather than " +
					"generated by BioT (for example `ADD_OWNER_ORGANIZATION_FILTER`). The API cannot change " +
					"an id, so changing it here destroys and recreates the action.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"value": schema.StringAttribute{
				Required: true,
				MarkdownDescription: "Name of the action implementation, for example " +
					"`AddSearchFilterAction` or `RemoveAttributesInParamsAction`. Only " +
					"`DYNAMIC` implementations can be created - BioT rejects " +
					"the built-in `CLASS` ones, and the error lists everything it accepts. " +
					"It cannot be changed once the action exists - to switch " +
					"implementation, give the action a new `id` as well.",
			},
			"description": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Default:             stringdefault.StaticString(""),
				MarkdownDescription: "Free-text description. Defaults to an empty string.",
			},
			"params": schema.StringAttribute{
				Optional: true,
				Computed: true,
				Default:  stringdefault.StaticString("{}"),
				MarkdownDescription: "Parameters for the action implementation, as a JSON " +
					"object. Build it with `jsonencode({...})`; formatting differences are " +
					"normalized away and will not show up as a diff.",
				PlanModifiers: []planmodifier.String{
					biotplanmodifiers.JsonNormalizePlanModifier{},
				},
			},
			"tags": schema.SetAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
				MarkdownDescription: "Tags applied to the action. Removing this from your " +
					"configuration keeps the tags BioT already has; set it to `[]` to clear " +
					"them.\n\nThe `<<BuiltIn>>` tag that BioT puts on its own actions is " +
					"not included here and cannot be set - use the `built_in` attribute " +
					"instead.",
			},
			"built_in": schema.BoolAttribute{
				Computed: true,
				MarkdownDescription: "Whether BioT ships this action. Built-in actions " +
					"can be imported and updated, but not destroyed.",
				PlanModifiers: []planmodifier.Bool{
					// Whether an action is built-in never changes, so keep the known value
					// rather than replanning it as "(known after apply)" on every change.
					boolplanmodifier.UseStateForUnknown(),
				},
			},
		},
	}
}

// ValidateConfig rejects the built-in marker in tags - see abac.RejectBuiltInTag.
func (r *BiotAbacActionResource) ValidateConfig(ctx context.Context, req resource.ValidateConfigRequest, resp *resource.ValidateConfigResponse) {
	var config TerraformAbacAction

	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	abac.RejectBuiltInTag(config.Tags, Entity, &resp.Diagnostics)
}

// ModifyPlan refuses a change of value on an existing action - see abac.RejectValueChange.
func (r *BiotAbacActionResource) ModifyPlan(ctx context.Context, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	abac.RejectValueChange(ctx, Entity, req, resp)
}

func (r *BiotAbacActionResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan TerraformAbacAction

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	createRequest, diags := MapTerraformActionToCreateRequest(ctx, plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	response, err := r.client.Abac.CreateAction(ctx, createRequest)
	if err != nil {
		abac.AddError(&resp.Diagnostics, Entity, "create", plan.ID.ValueString(), err)
		return
	}

	model, diags := MapActionResponseToTerraformModel(ctx, response)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, model)...)
}

func (r *BiotAbacActionResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state TerraformAbacAction

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	response, err := r.client.Abac.GetAction(ctx, state.ID.ValueString())
	if err != nil {
		if transport.IsNotFound(err) {
			// Gone from the backend - drop it from state so Terraform plans a create.
			resp.State.RemoveResource(ctx)
			return
		}
		abac.AddError(&resp.Diagnostics, Entity, "read", state.ID.ValueString(), err)
		return
	}

	model, diags := MapActionResponseToTerraformModel(ctx, response)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, model)...)
}

func (r *BiotAbacActionResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan TerraformAbacAction

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	updateRequest, diags := MapTerraformActionToUpdateRequest(ctx, plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	response, err := r.client.Abac.UpdateAction(ctx, plan.ID.ValueString(), updateRequest)
	if err != nil {
		abac.AddError(&resp.Diagnostics, Entity, "update", plan.ID.ValueString(), err)
		return
	}

	model, diags := MapActionResponseToTerraformModel(ctx, response)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, model)...)
}

func (r *BiotAbacActionResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state TerraformAbacAction

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	err := r.client.Abac.DeleteAction(ctx, state.ID.ValueString())
	if err != nil {
		if transport.IsNotFound(err) {
			// Already gone - deleting it is exactly what we wanted.
			return
		}
		abac.AddError(&resp.Diagnostics, Entity, "delete", state.ID.ValueString(), err)
	}
}

// Actions are imported by their id, which is the same id used in the configuration.
func (r *BiotAbacActionResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
